version: '3'

services:
  mongo:
    image: laterball/mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - laterball-network
  laterball:
    image: 'laterball/laterball-server:latest'
    depends_on:
      - 'mongo'
    ports:
      - 8080:8080
    networks:
      - laterball-network

volumes:
  mongo:

networks:
  laterball-network:
    driver: bridge