version: '3'

services:
  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
      - laterball-network

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - laterball-network
  mongo:
    image: laterball/mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - laterball-network
    env_file: .env.DEV
  laterball:
    container_name: laterball
    image: 'laterball/laterball-server:latest'
    depends_on:
      - 'mongo'
    ports:
      - 8080:8080
    networks:
      - laterball-network
    env_file: .env.DEV
  nginx:
    image: nginx
    volumes:
      - ./laterball.DEV.conf:/etc/nginx/conf.d/laterball.conf
    depends_on:
      - 'laterball'
    ports:
      - 80:80
    networks:
      - laterball-network

volumes:
  mongo:

networks:
  loki:
  laterball-network:
    driver: bridge