version: '3'

services:
  mongo:
    image: laterball/mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - laterball-network
  redis:
    image: redis:latest
    command: redis-server --save 300 1
    volumes:
      - redis-data:/data
    restart: always
  laterball:
    image: 'laterball/laterball-server'
    depends_on:
      - 'mongo'
      - 'redis'
    ports:
      - 8080:8080
    networks:
      - laterball-network

volumes:
  mongo:
  redis-data:


networks:
  laterball-network:
    driver: bridge