version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  laterball:
    image: 'laterball/laterball-server'
    depends_on:
      - 'mongo'
    ports:
      - 8080:8080

volumes:
  mongo: