version: '3'

services:
  laterball-mongo:
    image: laterball/mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  laterball:
    image: 'laterball/laterball-server'
    depends_on:
      - 'laterball-mongo'
    ports:
      - 8080:8080

volumes:
  mongo: