version: '3'

services:
  mongo:
    image: laterball/mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - laterball-network
    env_file: .env.PROD
  laterball:
    image: 'laterball/laterball-server:latest'
    depends_on:
      - 'mongo'
    volumes:
      - ./logs:/logs
    ports:
      - 8080:8080
    networks:
      - laterball-network
    env_file: .env.PROD
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 10

volumes:
  mongo:

networks:
  laterball-network:
    driver: bridge