FROM adoptopenjdk/openjdk8:latest

ARG VERSION
ARG MONGO_USER
ARG KTOR_ENV
ARG RAPID_API_KEY
ARG MONGO_USER
ARG MONGO_PASSWORD
ARG MONGO_HOST
ARG LATERBALL_TWITTER_API_KEY
ARG LATERBALL_TWITTER_API_SECRET
ARG LATERBALL_ACCESS_TOKEN
ARG LATERBALL_ACCESS_SECRET

ENV KTOR_ENV=${KTOR_ENV}
ENV RAPID_API_KEY=${RAPID_API_KEY}
ENV MONGO_USER=${MONGO_USER}
ENV MONGO_PASSWORD=${MONGO_PASSWORD}
ENV MONGO_HOST=${MONGO_HOST}
ENV LATERBALL_TWITTER_API_KEY=${LATERBALL_TWITTER_API_KEY}
ENV LATERBALL_TWITTER_API_SECRET=${LATERBALL_TWITTER_API_SECRET}
ENV LATERBALL_ACCESS_TOKEN=${LATERBALL_ACCESS_TOKEN}
ENV LATERBALL_ACCESS_SECRET=${LATERBALL_ACCESS_SECRET}

EXPOSE 8080
COPY build/distributions/laterball-server-$VERSION.tar .
WORKDIR /
RUN tar -xf laterball-server-$VERSION.tar && rm laterball-server-$VERSION.tar
CMD ["/laterball-server-2.4.3/bin/laterball-server"]