version: '3'

services:
  laterball:
    image: 'laterball/laterball-server'
    environment:
      - RAPID_API_KEY
      - LATERBALL_ANALYTICS_TAG
      - MONGO_USER
      - MONGO_PASSWORD
      - LATERBALL_TWITTER_API_KEY
      - LATERBALL_TWITTER_API_SECRET
      - LATERBALL_ACCESS_TOKEN
      - LATERBALL_ACCESS_SECRET