name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew assembleDist

      - name: Build docker images
        run: |
          VERSION=${GITHUB_REF##*/}
          echo "Building docker images for version $VERSION"
          ./scripts/builddocker.sh $VERSION PROD

      - name: Create tarballs
        run: |
          mkdir -p ./build/docker
          docker save laterball/laterball-server > ./build/docker/laterball-server.tar
          docker save laterball/mongo > ./build/docker/laterball-mongo.tar

      - name: Create .env.PROD file
        run: |
          cat <<EOF > .env.PROD
          KTOR_ENV=PROD
          MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
          MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
          RAPID_API_KEY=$RAPID_API_KEY
          MONGO_HOST=mongo
          CSRF_SECRET=$CSRF_SECRET
          COOKIE_DOMAIN=laterball.com
          BASE_URL=https://laterball.com
          EOF
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
          CSRF_SECRET: ${{ secrets.CSRF_SECRET }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Group deployment artifacts
        run: |
          mkdir -p build/deploy
          cp {docker-compose.PROD.yml,.env.PROD,nginx/laterball.PROD.conf,build/docker/*.tar} build/deploy

      - name: Copy artefacts to production
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/deploy/*"
          target: /usr/bin/laterball

      - name: Restart containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Loading docker images for $VERSION"
            cd /usr/bin/laterball/build/deploy
            docker load -i laterball-server.tar
            docker load -i laterball-mongo.tar
            docker compose -f docker-compose.PROD.yml down
            docker compose -f docker-compose.PROD.yml up -d --wait